# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build corne-ish_zen'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      alphas: '["qwerty"]'
